### PR TITLE
Enable codecov and remove CircleCI and Travis

### PR DESCRIPTION
**Pull request by foursixnine**
- Enable Codecov for GitHub Actions
- Remove CircleCI and Travis

### CODE REVIEW

**Comment by foursixnine** [comment]
Tests are all passing, I'm not sure yet why codecov is failing to upload the reports thoug... for now I will go ahead and merge

**Comment by Martchus** [comment]
Maybe the coverage data is stored at a location which is not preserved in the context `cover -report codecov` runs? (I had the problem once on os-autoinst when switching to an out-of-source-tree build.)

**Comment by foursixnine** [comment]
> Maybe the coverage data is stored at a location which is not preserved in the context `cover -report codecov` runs? (I had the problem once on os-autoinst when switching to an out-of-source-tree build.

I think the problem is kind of somewhere else... [Data is there](https://github.com/mudler/Mojo-IOLoop-ReadWriteProcess/runs/4380876668?check_suite_focus=true#step:7:1)

**Comment by perlpunk** [comment]
You should move to [Devel::Cover::Report::Codecovbash](https://metacpan.org/pod/Devel::Cover::Report::Codecovbash)
https://github.com/os-autoinst/os-autoinst/runs/4379650280?check_suite_focus=true#step:3:643
and also use a github action codecov/codecov-action to upload because there were some changes:
https://docs.codecov.com/docs/about-the-codecov-bash-uploader
https://github.com/os-autoinst/os-autoinst/blob/master/.github/workflows/ci.yml#L12

Note that although the bash uploader is marked as deprecated, that doesn't affect Devel::Cover::Report::Codecovbash because it is simply generating the JSON file, only the upload tool has been deprecated.

**Pull request merged**
