### PR TITLE
Fix flaky test failures in 01_run.t; improve tests

### PR DESCRIPTION
**Pull request by okurz**
* t: Fix flaky test failures in 01_run.t after removing timeout in "stop()"
* t: Generalize test for 'diag' to also accept format from perl debugger
* t: Prevent line wrap in test explanation string to prevent confusion
* t: Fix incorrect english spelling in explanation string
* t: Delete duplicate test line 'pipes are correctly disabled'

### CODE REVIEW

**Comment by okurz** [comment]
well, that didn't work: https://travis-ci.org/github/mudler/Mojo-IOLoop-ReadWriteProcess/jobs/665023160#L500 shows

```
t/01_run.t ............... 3/?     
    #   Failed test 'Still able to get stdout output, always in getline()'
    #   at t/01_run.t line 196.
    #          got: undef
    #     expected: 'TEST normal print
    # '
    # Looks like you failed 1 test of 37.
t/01_run.t ............... 4/? 
```

*sigh*. Not sure what to do next.

**Comment by okurz** [comment]
Ok, managed to fix all problems, I guess. Thanks to @Martchus for the productive pair-programming session :)

**Comment by okurz** [comment]
@mudler @foursixnine could you take a look please? All tests are stable now, I improved tests and would appreciate if we can have this patch merged and a new release of the package published.

**Comment by mudler** [comment]
Done! Thank you!

**Pull request merged**
