### PR TITLE
Enable GitHub Actions

### PR DESCRIPTION
**Pull request by foursixnine**

### CODE REVIEW

**Comment by Martchus** [comment]
Generally a good idea. Can we see whether it works somewhere?

**Comment by foursixnine** [comment]
@Martchus I'm debugging atm why its taking so [long](https://github.com/foursixnine/Mojo-IOLoop-ReadWriteProcess/runs/4365661553?check_suite_focus=true)

**Comment by foursixnine** [comment]
Waiting for CI now, however I'm pretty confident that it will at least execute [alltogether](https://github.com/foursixnine/Mojo-IOLoop-ReadWriteProcess/actions/runs/1521841517)

**Comment by foursixnine** [comment]
And we're a go!

**Pull request merged**
